### PR TITLE
Merged MIT and GPLv2 license texts to one file, licence field in bowe…

### PR DESCRIPTION
**Pull request by bpervan**
Created merged license file, "licence" field in bower.json points to that file

### CODE REVIEW

**Comment by sporritt** [comment]
cool, thanks!

**Comment by bpervan** [comment]
Thanks for the merge. Just one more thing. It looks like WebJar auto deployment system reads git repo by tags, and thus won't (or can't) import bower repo from master branch. Could we tag current HEAD with 2.0.5 or, let's say, 2.0.5.1 if you don't want to reuse/overwrite old tags? I could create new pull request in both cases.

**Comment by sporritt** [comment]
2.0.5.1 would be my preference...

**Comment by bpervan** [comment]
It seems that I can't file a pull request with (2.0.5.1) tag

http://stackoverflow.com/questions/12278660/adding-tags-to-a-pull-request

Could you, pls, tag current HEAD with 2.0.5.1 or however you want? Thanks in advance

**Comment by sporritt** [comment]
here you go

https://github.com/sporritt/jsPlumb/releases/tag/2.0.5.1

**Comment by bpervan** [comment]
awesome, thanks :)

**Pull request merged**
