### PR TITLE
Node drag events

### PR DESCRIPTION
**Pull request by lbicknese**
I added fire calls to node drag events. This way the movement of the nodes can be watched just like connections.

### CODE REVIEW

**Comment by sporritt** [comment]
Hello

Thanks for this. Did you know you can provide 'drag', 'stop', and 'start' callbacks in an options object as the second argument to jsPlumb.draggable? Does that do what you need?

**Comment by sporritt** [comment]
ok no problem. i'll leave this PR open until you confirm.

**Comment by lbicknese** [comment]
The stop callback is exactly what I needed. Thanks for your help, and
please close my pull request.

**Comment by sporritt** [comment]
thanks for the update.

**Comment by chj-damon** [comment]
@sporritt what do you mean that 'drag', 'stop', and 'start' callbacks in an options object as the second argument to jsPlumb.draggable? Is it like this:
instance.draggable(node, {
    'start': function() {},
    'drag': function() {},
    'stop': function() {}
})?

**Comment by chj-damon** [comment]
@sporritt thanks for pointing this very helpful configuration. I tried in my project and it works great!

**Pull request closed without merging**
