### PR TITLE
Fix for multiple dragging

### PR DESCRIPTION
**Pull request by Helen1987**
It's a suggestion how to fix bug #533. It's not correct for 100%. I need further clarifications about `ghostProxyOffsets`to fix it properly.

### CODE REVIEW

**Comment by sporritt** [comment]
thanks for this. i havent got time to look over this right now, unfortunately. it's gonna take me a couple of weeks probably before i can get to looking at this.

**Comment by sporritt** [comment]
@Helen1987 can you explain your use case for needing to be able to force the element to be draggable twice?

**Comment by Helen1987** [comment]
I have a rerender function which sets all nodes to draggable and adds required endpoints and connections after jsPlumb.reset. In some cases, nodes are completely new, sometimes an existing one. In the second case I got an exception. 
Node is html element.

**Comment by sporritt** [comment]
Ok so in that case i'd suggest the issue is that jsPlumb.reset should have removed the draggable functionality from each element.

**Comment by Helen1987** [comment]
Yeah, sounds good

**Comment by sporritt** [comment]
@Helen1987 that would need to start in [katavorio](https://github.com/jsplumb/katavorio/issues/30)

but as that issue says, unbinding everything could get slow. i see elsewhere in jsplumb's issue list you're talking about 3000 endpoints, so i gather you're dealing with quite a few elements, but have you considered just blowing away all your DOM elements and getting a new instance of jsPlumb instead of calling `reset` ?

**Comment by Helen1987** [comment]
Hm... For some reason I thought that calling reset is more efficent than creating a new instance. Ok, I'll do some research. But now resetting (not only jsPlumb.reset call) took not more than 2s, but adding new endpoints is 6-15 sec... Anyway, is it possible to destroy jsPlumb instance or setting it to null is enough?

**Comment by Helen1987** [comment]
Yes, seems it is faster to create a new instance and delete all svg elements manually... But overall time to re-render is the same( hope I will not have any memory leaks

**Comment by Helen1987** [comment]
wait, I realized recreating jsPlumb instance does not work:
```
isAlreadyDraggable: function (el) {
           return el._katavorioDrag != null;
},
```
`isAlreadyDraggable` does not care about jsPlumb instance, it check only the element(

**Comment by sporritt** [comment]
yes, my suggestion was you remove _all_ DOM elements and recreate.

**Comment by Helen1987** [comment]
I prefer to avoid removing all DOM elements

**Pull request closed without merging**
